### ISSUE TITLE
Reduce traffic to backends

### ISSUE THREAD

**Issue by ajavadia** [QISKit/qiskit-tutorial#104]
In many places in the tutorial the real backend to run on is hardcoded. When many users run tutorials, this creates a problem of overloading some backends and starving others. 

The problem is aggravated when one of the overloaded backends goes offline for maintenance, creating very long queues.

A potential solution is to not hardcode the backends. Rather, the tutorial codes must query the backends for availability, and also randomize the backend selection so it gets distributed across users. (In particular, often the tutorials run on 5 qubits. But they could as well run on the 16 qubit device).

## Your Environment

* Tutorial branch (stable/master):
* QISKit SDK version:
* Python version:

**Comment by rraymondhp** [comment]
Hi, another solution is to save the results of all tutorials in the cache (possibly renewing them after every calibration). It is most likely that people will run tutorials without altering the qasm/circuits. In this case, we can just use the cache. This is already done in IBM Quantum Experience (web-based IBM Q Systems)

**Comment by jaygambetta** [comment]
I added this to the getting started. With the update to qiskit 0.5 it will be nicer but this works. @attp when you go through the tutorials i think we want to have a similar function.

**Comment by rraymondhp** [comment]
I think this function should be implemented in qiskit or at IBM Q API. I do not think it is wise to ask users to do the load balancing because there are many factors to obtain the best balancing. If users are asked to do so, they will do so greedily and it may not lead to optimal balancing.

Another factor is that we have to take into account many factors, such as, the number of qubits, layouts, gate fidelity, etc when choosing which backend that can run a program.

**Comment by ajavadia** [comment]
Resolved by the above PR in the SDK. When merged, I will go through tutorials and update them accordingly.

**Comment by rraymondhp** [comment]
We have shown how to choose the least busy device at the tutorial.
