### ISSUE TITLE
why the util folder

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-tutorial#277]
## Your Environment

* QISKit version:
* Python version:
@diego-plan9 do we need the utils folder.

**Comment by diego-plan9** [comment]
It was used previously for other purposes, but at the moment is just for being able to run the tutorials as tests via the command line - see #151. I don't think it has been really used for this purpose, but by doing it that way, errors due to changes in the versions can be changed more systematically, opening the door for running travis or similar.

**Comment by jaygambetta** [comment]
Ok

we can keep it for now even though we don't use it.
