### ISSUE TITLE
CNOT representation in "superposition and entanglement"

### ISSUE THREAD

**Issue by dtchang** [QISKit/qiskit-tutorial#48]
The CNOT representation should follow the standard (Wiki, Nielson & Chuang, etc.) used in the quantum community. A non-standard, IBM Q unique, representation is not helpful to the user.

**Comment by rraymondhp** [comment]
Hi,
I agree with you that the standard notation is the best. This can be done once we swap the order of the qubits, from left to right instead of the current from right to left. I have noticed this in this tutorial: 
https://nbviewer.jupyter.org/github/QISKit/qiskit-tutorial/blob/master/1_introduction/quantum_gates_and_linear_algebra.ipynb

```
In the hereafter, following the standard in the quantum community we treat the order of the qubits from left to right, namely, the least significant bit (LSB) is the left-most qubit. Thus, the tensor product of q0, q1, and q2 of the three qubits is defined as q0⊗q1⊗q2

.

Notice that the IBM Quantum experience uses order the qubits in the opposite way (the tensor product is q2⊗q1⊗q0
). Thus to get the standard order, we must store the measurement of the first qubit to the last bit, the second qubit to the second last bit, and so on.
```

**Comment by jaygambetta** [comment]
@dtchang was discuss many times between us. Either you have to give up on the standard bits order, or the standard tensor order of gates using by quantum text books. Since the computer science community is much larger than quantum we decided to go with the standard bit order and have 0001 be qubit 0 in the excited state. It make associating the classical outcome with the bits simpler. The tutorials/user guides need more work to describe this.
